global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: azure
  isHubCluster: false

  namespaces:
    - bubble-animation

  projects:
    - bubble-animation

  applications:
    bubble-app:
      name: bubble-app
      namespace: bubble-animation
      project: bubble-animation
      path: charts/azure/bubble-animation

