---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-storage-nodes
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: label-storage-nodes
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - consoles
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - "operator.openshift.io"
    resources:
      - consoles
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-storage-nodes
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
subjects:
  - kind: ServiceAccount
    name: label-storage-nodes
    namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: label-storage-nodes
---